### PR TITLE
Pr validation

### PR DESCRIPTION
**Pull request by eaba**
## Change
- GitHub Actions (PR Validation)
  - Akka.ShoppingCart.Tests
  - Akka.ShoppingCart.Api.Tests
- Dependabot
- Needs to be updated to [Akka.Hosting](http://akka.hosting/) / Management 1.0
- Akka.HealthCheck support

### CODE REVIEW

**Review by Aaronontheweb — CHANGES_REQUESTED** [review]
Let's only do GitHub Actions on this PR, not everything all at once.

**Comment by Aaronontheweb** [comment]
The API tests look good - let's stick with those. Don't worry about testing the Blazor UI.

**Comment by eaba** [comment]
@Aaronontheweb I remove that. Everything will change to `API`: API - HTTPCLIENT - Blazor UI......you understand?

**Comment by Aaronontheweb** [comment]
> @Aaronontheweb I remove that. Everything will change to `API`: API - HTTPCLIENT - Blazor UI......you understand?

if you have to rewrite the app in order to make it testable, try again - change your tests.

**Pull request closed without merging**
